config setup
    charondebug="ike 2, knl 2, cfg 2"

conn bot2root-vpn
    type=tunnel
    keyexchange=ikev1
    aggressive=yes
    authby=psk
    left=%any
    leftid=bot2root-vpn
    right=%any
    ike=3des-sha1-modp1024
    esp=3des-sha1
    auto=add
